apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-app
  labels:
{{ include "service.labels.standard" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
{{ include "service.labels.standard" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "service.labels.standard" . | indent 8 }}
    spec:
      initContainers:
      - name: mysqlcheck
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        env:
        - name: MYSQL_HOST
          value: mysql 
        - name: MYSQL_DB
          value: {{ .Values.env.MYSQL_DB }}
        - name: MYSQL_PORT
          valueFrom:
            secretKeyRef:
              name: {{ .Chart.Name }}-secret
              key: MYSQL_PORT
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Chart.Name }}-secret
              key: MYSQL_USER
        - name: MYSQL_PASS
          valueFrom:
            secretKeyRef:
              name: {{ .Chart.Name }}-secret
              key: MYSQL_PASS
        args:
        - -c
        - "while ! mysqlcheck --host=\"${MYSQL_HOST}\" --port=\"${MYSQL_PORT}\" --user=\"${MYSQL_USER}\" --password=\"${MYSQL_PASS}\" --databases \"${MYSQL_DB}\" ; do sleep 1; done"
        command:
        - /bin/sh
      containers:
      - name:  {{ .Chart.Name }}-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command: ["/bin/sh","-c","while true;do echo \"hello world\" ;sleep 1;done"]
