apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
  labels:
{{ include "service.labels.standard" . | indent 4 }}
type: Opaque
data:
  MYSQL_PORT: {{ include "mysql.port" . | b64enc | quote }}
  MYSQL_USER: {{ include "mysql.user" . | b64enc | quote }}
  MYSQL_PASS: {{ include "mysql.pass" . | b64enc | quote }}